### PR TITLE
Add default charset conversion from default UTF-16LE to LS UTF-8

### LINKED ISSUE #3: Add charset or codec support
originally reported here:  https://github.com/elasticsearch/logstash/issues/2139

The eventlog input doesn't invoke @codec at all, so users can't change charset or other codec settings.

I don't know what fields from the Eventlog need to be decoded, though, maybe _just_ message? Maybe all of them?

This might be weird given the codec system acts, for inputs, as a deserialization, but with eventlog we already have an object and there's nothing to deserialize.

It's possible "codec" doesn't make sense for eventlogs, but instead we could provide a charset setting. Needs more research.

### PR DESCRIPTION
**Pull request by purbon**
This PR adds an encoding converter for all string fields that will take care of converting the default eventlog UTF-16LE to the LogStash UTF-8 encoding.
### notes to reviewers:
1. According to my findings (https://github.com/djberg96/win32-eventlog/blob/bd236da2383979a83f25541e9be68a4f3b3234fe/lib/win32/eventlog.rb#L923) all strings received from eventlog will be defaulted to UTF-16LE encoding, so end of the day the best approach to enforce the conversion is to keep this transparent to the user.
2. Some testing has been done with this PR, but certainly windows is not a land where I feel extremely comfortable. Open to all kind of comments, specially testing that involve the usage of non western languages like Japanese.

Fixes #3

### CODE REVIEW

**Comment by jordansissel** [comment]
Related: https://github.com/elastic/logstash/issues/2139

**Comment by masaruh** [comment]
Tried this on Windows Server 2012 R2 Japanese.
Messages were correctly retrieved using `charset => CP932`.

**Comment by jordansissel** [comment]
I did some digging in the win32-eventlog library and posted my notes in an [issue on win32-eventlog](https://github.com/djberg96/win32-eventlog/issues/19#issuecomment-239730906).

**Comment by ph** [comment]
@jordansissel but until the lib we are using move to native *UNICODE* calls, is using the *ANSI* calls and correctly converting them is a good solution for now.

Are we at risk of having truncated data?

@masaruh In you testing you did not encounter any truncated data?

**Comment by jordansissel** [comment]
@ph I'm not sure. the ANSI calls seem to return `?` for unrepresentable characters, so the ANSI calls actually lose data in the translation process.

This PR currently sets the default charset to `UTF16-LE` and I don't think that's correct given the calls win32-eventlog makes are using the ANSI methods -- at best, you'll probably get CP1252, Latin1, or Shift_JIS, or similar, as the encoding but with valid-Unicode-but-invalid-ANSIwhatever you'll still get data loss. :\

**Comment by jordansissel** [comment]
My preference is to fix the win32-eventlog library to allow the Unicode method calls to be used.

**Comment by ph** [comment]
@jordansissel Encoding is hard, Yeah I agree we should fix the bug upstream with using the right system call to retrieve valid unicode, fixing at the source will make sure we do our best to get the orignial data without truncated message. :(

**Comment by jordansissel** [comment]
I think this is OK to merge given the upstream win32-eventlog issue is still open.

**Pull request merged**
