### PR TITLE
add several fixes to ensure eventlog works

### LINKED ISSUE #9: "Windows Event Log error: Invoke of: NextEvent" error on Windows Server 2012 R2
(This issue was originally filed by @tuespetre at https://github.com/elastic/logstash/issues/2906)

---

When I try to use the `eventlog` input like so in my configuration file:

```
input {
  eventlog {
    type => 'winevt'
  }
}

output {
  ...
}
```

The log gets blasted with these errors (this is one, whole, intact message):

```
{:timestamp=>"2015-03-26T13:21:14.601000-0500", :message=>"Windows Event Log error: Invoke of: NextEvent\nSource: SWbemEventSource\nDescription: Timed out \n\n[\"org.racob.com.Dispatch.invokev(Native Method)\", \"org.racob.com.Dispatch.invokev(Dispatch.java:243)\", \"org.racob.com.Dispatch.callN(Dispatch.java:187)\", \"org.jruby.ext.win32ole.RubyWIN32OLE.invokeMethodOrGet(RubyWIN32OLE.java:205)\", \"org.jruby.ext.win32ole.RubyWIN32OLE.method_missing(RubyWIN32OLE.java:113)\", \"org.jruby.ext.win32ole.RubyWIN32OLE$INVOKER$i$0$0$method_missing.call(RubyWIN32OLE$INVOKER$i$0$0$method_missing.gen)\", \"org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:677)\", \"org.jruby.runtime.Helpers$MethodMissingMethod.call(Helpers.java:452)\", \"org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:210)\", \"org.jruby.runtime.callsite.CachingCallSite.callMethodMissing(CachingCallSite.java:401)\", \"org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:323)\", \"org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)\", \"org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)\", \"org.jruby.ast.DAsgnNode.interpret(DAsgnNode.java:110)\", \"org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)\", \"org.jruby.ast.BlockNode.interpret(BlockNode.java:71)\", \"org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)\", \"org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)\", \"org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:157)\", \"org.jruby.runtime.Interpreted19Block.yieldSpecific(Interpreted19Block.java:130)\", \"org.jruby.runtime.Block.yieldSpecific(Block.java:111)\", \"org.jruby.RubyKernel.loop(RubyKernel.java:1507)\", \"org.jruby.RubyKernel$INVOKER$s$0$0$loop.call(RubyKernel$INVOKER$s$0$0$loop.gen)\", \"org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:316)\", \"org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:145)\", \"org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)\", \"org.jruby.ast.FCallNoArgBlockNode.interpret(FCallNoArgBlockNode.java:32)\", \"org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)\", \"org.jruby.ast.BlockNode.interpret(BlockNode.java:71)\", \"org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)\", \"org.jruby.ast.RescueNode.interpret(RescueNode.java:116)\", \"org.jruby.ast.BeginNode.interpret(BeginNode.java:83)\", \"org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)\", \"org.jruby.ast.BlockNode.interpret(BlockNode.java:71)\", \"org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)\", \"org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)\", \"org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)\", \"org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)\", \"org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)\", \"org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)\", \"org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)\", \"org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)\", \"org.jruby.ast.RescueNode.interpret(RescueNode.java:116)\", \"org.jruby.ast.BeginNode.interpret(BeginNode.java:83)\", \"org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)\", \"org.jruby.ast.BlockNode.interpret(BlockNode.java:71)\", \"org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)\", \"org.jruby.ast.RescueNode.interpret(RescueNode.java:116)\", \"org.jruby.ast.EnsureNode.interpret(EnsureNode.java:96)\", \"org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)\", \"org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)\", \"org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)\", \"org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)\", \"org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)\", \"org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)\", \"org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)\", \"org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)\", \"org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)\", \"org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)\", \"org.jruby.runtime.Block.call(Block.java:101)\", \"org.jruby.RubyProc.call(RubyProc.java:290)\", \"org.jruby.RubyProc.call(RubyProc.java:228)\", \"org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:99)\", \"java.lang.Thread.run(Thread.java:745)\"]", :level=>:error}
```

Judging from the code here the timeout is 1 second:

https://github.com/logstash-plugins/logstash-input-eventlog/blob/master/lib/logstash/inputs/eventlog.rb#L54

I cannot figure out why this is timing out, though. Another thing is that the log will just fill way up with these gigantic errors, easily creating megs upon megs (I almost got up to a gig) of log data that is really redundant and unnecessary, I would almost expect the input to give up after it hits an error like this and log a more concise error to the log for diagnostics.

### PR DESCRIPTION
**Pull request by jsvd**
* abort early if wmi_query has a fatal or permanent error
* wrap NextEvent(1000) in begin/rescue to silence timeout exceptions
* keep timeout in NextEvent to ensure plugin exits
* reduced code complexity by eliminating one begin block level
* no longer rescue Exception, only StandardError

addresses #7 
fixes #9

### CODE REVIEW

**Comment by ESamir** [comment]
++

**Comment by ashangit** [comment]
++

**Comment by ph** [comment]
@jsvd LGTM, tested on Windows Server 2012 R2 with a low event rate.

**Comment by gzpbx** [comment]
Has this fix been published to https://rubygems.org/gems/logstash-input-eventlog ?
I still encounter the NextEvent(timeout) issue after "plugin update logstash-input-eventlog"

**Pull request closed without merging**
