### PR TITLE
Manual merge from https://github.com/manusfreedom/logstash

### PR DESCRIPTION
**Pull request by manusfreedom**
* New eventlog inputs:
- No gem or Win32OLE required, use "win32/registry" and FFI
- Not use WMI (memory leak in svchost.exe because of Security Token)
- Optimized memory and fixed some memory leak
- More compatible with old version
- Fix crash/memory leak on build Description
- Fix crash on registry with null byte

It's to follow https://github.com/elastic/logstash/pull/1419
JIRA Issue:
https://logstash.jira.com/browse/LOGSTASH-1506

Can be merged.

### CODE REVIEW

**Comment by manusfreedom** [comment]
For the moment, we deployed it on 50 servers and it works without problem.

**Comment by manusfreedom** [comment]
All last commits pushed the 50 servers.

**Comment by manusfreedom** [comment]
Works well on 120 servers.
It can be merge.

**Comment by galindro** [comment]
As I understand, this PR will include the fix for a bug ticket opened by me (https://github.com/elastic/logstash/blob/master/CHANGELOG.md). I that right? When this will be merged into master? When this is merged into master, the version 1.5.1 available for download [here](https://download.elastic.co/logstash/logstash/logstash-1.5.1.zip) will be updated with this fix or a new release will be launched?

**Comment by suyograo** [comment]
Closing this as #21 introduced win32eventlog

**Pull request closed without merging**
